config/routes.rb
Rails.application.routes.draw do

root "rumors#index"

resources :rumors

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rumor.rb
class Rumor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello world"
  end

end

app/controllers/rumors_controller.rb
class RumorsController < ApplicationController
  def index
    @rumors = Rumor.all
  end

  def new
#    @rumor = Rumor.new
  end

  def create
    @rumor = Rumor.new
    @rumor.a_author = params[:a_author]
    @rumor.content = params[:content]
    @rumor.save
    #    if @rumor.save
    #      flash[:success] = "Rumor Shared"
    #    else
    #      flash[:error] = "Problem while saving"
    #    end
    redirect_to rumor_path(@rumor.id)
  end

def show
  @rumor = Rumor.find(params[:id])
end

def edit
  @rumor = Rumor.find(params[:id])
end

def update
  @rumor = Rumor.find(params[:id])
  @rumor.update(rumor_params)
  redirect_to root_path
end

def destroy
  @rumor = Rumor.find(params[:id])
  @rumor.destroy
  redirect_to root_path
end

private
  def rumor_params
    params.require(:rumor).permit(:a_author, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rumors_helper.rb
module RumorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render "shared/navbar" %>
  </body>
</html>

app/views/rumors/edit.html.erb
<h1>Edit</h1>

  <%= form_tag rumor_path(@rumor), method: :put do %>

  <%= label_tag 'a_author', 'Author' %>
  </br>
  <%= text_field_tag 'a_author', @rumor.a_author%>
  </br>
  </br>
  <%= label_tag 'content', 'Edit content' %>
  </br>
  <%= text_area_tag "content", @rumor.content, :size =>"60x10" %>
  </br>

  <%= submit_tag 'Edit' %>
<% end %>

app/views/rumors/index.html.erb
<h1>Gossip list</h1>

  <% @rumors.each do |r| %>

<table>
    <tr>
        <th>Rumor</th>
        <th>From</th>
        <th>Action</th>
    </tr>
    <tr>
        <td><%= r.content %></td>
        <td><%= r.a_author %></td>
        <td>
        <%= link_to 'Show', rumor_path(r) %> -
        <%= link_to 'Edit', edit_rumor_path(r) %> -
        <%= link_to 'Delete', rumor_path(r),
              method: :delete,
              data: {confirm: 'Are you sure ?'} %>
        </td>
    </tr>
</br>

</table>

  <% end %>

app/views/rumors/new.html.erb
<h1>New Gossip</h1>

<%= form_tag rumors_path do %>

  <%= label_tag 'a_author', "Author  : " %>
  <%= text_field_tag "a_author" %></br>
  </br>

  <%= label_tag 'content', "Content : " %>
  <%= text_area_tag "content", nil,:size =>"60x10" %></br>
  </br>

  <%= submit_tag "Create" %></br>
  </br>

<% end %>

app/views/rumors/show.html.erb
<h1>Check rumor</h1>

<h2>sent from <%= @rumor.a_author %></h2>
<p><%= @rumor.content %></p>

<%= link_to "Edit this rumor", edit_rumor_path %> - <%= link_to 'Delete', rumor_path(@rumor),
      method: :delete,
      data: {confirm: 'Are you sure you want to delete this rumor ?'} %>

app/views/shared/_navbar.html.erb
</br>
</br>
</br>
= 🗣️ = 🗣️ = 🗣️ = 🗣️ = 🗣️ = 🗣️ = 🗣️ = 🗣️ = 🗣️ = 🗣️ = 🗣️ = 🗣️ = 🗣️ = 🗣️ =

<p><%= link_to "Send a rumor", new_rumor_path %> - <%= link_to 'List of rumors', rumors_path %></p>